
let RAW=[]; const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:n>=1e6?'compact':'standard',maximumFractionDigits:n>=1e6?2:0}).format(n||0); const num=n=>new Intl.NumberFormat('en-US').format(Math.round(n||0)); const pct=n=>`${(n||0).toFixed(1)}%`;
async function load(){RAW=await fetch('data/transactions.json').then(r=>r.json()); initFilters(); update();}
function initFilters(){const vals=k=>[...new Set(RAW.map(x=>x[k]))].sort(); for(const [id,k] of [['region','Region'],['category','Category'],['channel','Channel']]){const el=document.getElementById(id); if(!el)continue; vals(k).forEach(v=>el.add(new Option(v,v))); el.onchange=update;} const min=document.getElementById('start'),max=document.getElementById('end'); if(min){min.value='2024-11-01';max.value='2026-10-31';min.onchange=max.onchange=update}}
function filtered(){const get=id=>document.getElementById(id)?.value||'All'; const s=document.getElementById('start')?.value,e=document.getElementById('end')?.value;return RAW.filter(x=>(get('region')==='All'||x.Region===get('region'))&&(get('category')==='All'||x.Category===get('category'))&&(get('channel')==='All'||x.Channel===get('channel'))&&(!s||x.OrderDate>=s)&&(!e||x.OrderDate<=e))}
function sum(a,k){return a.reduce((t,x)=>t+(+x[k]||0),0)} function group(a,k,v='Revenue'){const m={};a.forEach(x=>m[x[k]]=(m[x[k]]||0)+(+x[v]||0));return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function set(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function bars(id,rows,formatter=money){const e=document.getElementById(id);if(!e)return;const max=Math.max(1,...rows.map(x=>x[1]));e.innerHTML=rows.slice(0,7).map(([k,v])=>`<tr><td>${k}</td><td><div class="bar"><i style="width:${v/max*100}%"></i></div></td><td class="num">${formatter(v)}</td></tr>`).join('')||'<tr><td colspan="3">No matching data</td></tr>'}
function line(id,rows){const e=document.getElementById(id);if(!e)return;if(!rows.length){e.innerHTML='<div class="empty">No matching data</div>';return}const W=700,H=210,p=20,max=Math.max(...rows.map(x=>x[1])),min=Math.min(...rows.map(x=>x[1]));const pts=rows.map((x,i)=>`${p+i*(W-2*p)/Math.max(1,rows.length-1)},${H-p-(x[1]-min)*(H-2*p)/Math.max(1,max-min)}`).join(' ');e.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="trend chart"><line x1="${p}" y1="${H-p}" x2="${W-p}" y2="${H-p}" stroke="#dfe5ed"/><polyline points="${pts}" fill="none" stroke="var(--accent)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function monthGroup(a,v='Revenue'){const m={};a.forEach(x=>{const k=x.OrderDate.slice(0,7);m[k]=(m[k]||0)+(+x[v]||0)});return Object.entries(m).sort()}
function update(){const a=filtered(); const revenue=sum(a,'Revenue'),cogs=sum(a,'COGS'),opex=sum(a,'OpEx'),marketing=sum(a,'MarketingSpend'),profit=revenue-cogs-opex-marketing,units=sum(a,'UnitsSold'); const dash=document.body.dataset.dashboard;
 if(dash==='sales'){set('k1',money(revenue));set('k2',num(units));set('k3',money(revenue/Math.max(1,a.length)));set('k4',num(new Set(a.map(x=>x.OrderID)).size));line('trend',monthGroup(a));bars('rank1',group(a,'Region'));bars('rank2',group(a,'Product'));}
 if(dash==='profit'){set('k1',pct(100*(revenue-cogs)/Math.max(1,revenue)));set('k2',money(profit));set('k3',money(cogs));set('k4',money(opex));line('trend',monthGroup(a,'Revenue').map(([m])=>[m,monthGroup(a.filter(x=>x.OrderDate.startsWith(m)),'Revenue').length?sum(a.filter(x=>x.OrderDate.startsWith(m)),'Revenue')-sum(a.filter(x=>x.OrderDate.startsWith(m)),'COGS')-sum(a.filter(x=>x.OrderDate.startsWith(m)),'OpEx')-sum(a.filter(x=>x.OrderDate.startsWith(m)),'MarketingSpend'):0]));bars('rank1',group(a,'Category').map(([k])=>{const z=a.filter(x=>x.Category===k),r=sum(z,'Revenue');return[k,100*(r-sum(z,'COGS'))/Math.max(1,r)]}),pct);bars('rank2',[['COGS',cogs],['Operating expense',opex],['Marketing',marketing]]);}
 if(dash==='regional'){const regs=group(a,'Region');set('k1',regs[0]?.[0]||'—');set('k2',regs[0]?money(regs[0][1]):'—');set('k3',num(regs.length));set('k4',regs.at(-1)?.[0]||'—');bars('rank1',regs);line('trend',monthGroup(a)); const t=document.getElementById('matrix'); if(t){const cats=[...new Set(a.map(x=>x.Category))].sort();t.innerHTML='<tr><th>Region</th>'+cats.map(c=>`<th class="num">${c}</th>`).join('')+'</tr>'+regs.map(([r])=>`<tr><td>${r}</td>${cats.map(c=>`<td class="num">${money(sum(a.filter(x=>x.Region===r&&x.Category===c),'Revenue'))}</td>`).join('')}</tr>`).join('')}}
 set('rows',num(a.length));}
load();
